apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot
  namespace: maple-raid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      containers:
        - name: bot
          image: minqq/presentation:latest
          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: maple-secrets
                  key: db_connection
            - name: Discord__BotToken
              valueFrom:
                secretKeyRef:
                  name: maple-secrets
                  key: discord_bot_token
            - name: Discord__ChannelId
              value: "840590742270771223"
            - name: App__AppUrl
              value: https://maplestory.paralleluniversegame.uk
