apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data
  namespace: maple-raid
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: maple-raid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: postgres
          image: postgres:18
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_DB
              value: presentationdb
            - name: POSTGRES_PASSWORD_FILE
              value: /run/secrets/postgres_password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql
            - name: secrets
              mountPath: /run/secrets
              readOnly: true
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-data
        - name: secrets
          secret:
            secretName: maple-secrets
            items:
              - key: postgres_password
                path: postgres_password
---
apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: maple-raid
spec:
  selector:
    app: database
  ports:
    - port: 5432
      targetPort: 5432
