import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {RolesProvider} from "./providers/RolesProvider";
import {cookies} from "next/headers";
import NavBar from "./navbar/page";
import ClientThemeProvider from "./providers/ClientThemeProvider";
import {LoadingProvider} from "./providers/LoadingContext";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
                                             children,
                                         }: Readonly<{
    children: React.ReactNode;
}>) {
    const cookieStore = await cookies();
    const discordId = cookieStore.get("discordId")?.value;
    const sessionId = cookieStore.get(`sessionId${discordId}`)?.value;
    const jwtToken = cookieStore.get("jwtToken")?.value;
    let initialRole = "";
    if (sessionId) {
        initialRole = "admin";
    } else if (jwtToken) {
        initialRole = "user";
    }

    return (
        <html lang="en" suppressHydrationWarning>
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <ClientThemeProvider>
            <RolesProvider initialRole={initialRole}>
                <NavBar></NavBar>
                <LoadingProvider>{children}</LoadingProvider>
            </RolesProvider>
        </ClientThemeProvider>
        </body>
        </html>
    );
}

